name: Windows

on: [push, pull_request]

jobs:
  build-win10:
    strategy:
      matrix:
        toolset: [x64]
        config: [Release]
        
    runs-on: windows-latest    
    name: Windows 10, ${{ matrix.config }} ${{ matrix.toolset }}
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install Boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
        boost-version: 1.73.0
        toolset: msvc14.2
        boost_instal_dir: C:\Repos
   
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config}}
      env: 
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      
    - name: Build  
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config}}  
      env: 
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
